# Site settings
title: Oscaner
SEOTitle: Oscaner 的博客 | Oscaner Blog
# logo: ""
header-img: assets/img/home-bg.jpg
email: oscaner1997@gmail.com
description: "心若浮沉，浅笑安然"
keyword: "Kang Oscaner China Blog"
url: 'https://www.oscaner.com'              # your host, for absolute URL
baseurl: ''                             # for example, '/blog' if your blog hosted on 'host/blog'
record:
  name: '浙ICP备17039697号-2'
  link: 'https://beian.miit.gov.cn'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: Oscaner
zhihu_username: oscaner
github_username: Oscaner
# twitter_username: Oscaner1
# facebook_username: ''
# linkedin_username: firstname-lastname-idxxxx
bilibili_uid: 17118231


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: /:simple_path/:title.html
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
    "_directories/*.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

pagination:
  enabled: true
  per_page: 10
  offset: 0
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true


collections:
  navbar:
    output: true
    permalink: /:title/
  directories:
    output: true
    permalink: /:directory_path/


# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins:
  - jekyll-paginate-v2
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-wikilinks
  - jekyll-mermaid


jekyll-spaceship:
  processors:
    - table-processor
    - emoji-processor


# Sitemap settings
defaults:
  -
    scope:
      path: "googlee58ffc7a9a1ba566.html"
    values:
      sitemap: false
  -
    scope:
      path: "baidu_verify_code-RlNzeiqm6B.html"
    values:
      sitemap: false


# Wikilinks.
wikilinks:
  attributes:
    enabled: true
  css:
    exclude: []
    name:
      typed: 'typed'
      wiki: 'wiki-link'
      web: 'web-link'
      invalid_wiki: 'invalid-wiki-link'
      embed_container: 'embed-container'
      embed_title: 'embed-title'
      embed_content: 'embed-content'
      embed_link: 'embed-wiki-link'
      embed_image_container: 'embed-image-container'
      embed_image: 'embed-image'
  enabled: true
  exclude: []


# Mermaid.
mermaid:
  src: '/packages/mermaid/9.1.6/mermaid.min.js'


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus:
  enable: false
  username: oscaner


# Gitalk settings
gitalk:
  enable: true
  client_id: "f86fb5601466c278f223"
  client_secret: "8234184af9a4cbc9dfa58bbea7ff6cdb84d33f1f"
  repo: "oscaner.github.io"
  owner: "Oscaner"
  admin: ["Oscaner"]


# Netease settings
netease:
  comment: false


# Baidu
baidu:
  # Baidu site verification
  site_verification: 'code-RlNzeiqm6B'
  # Baidu Analytics
  analytics:
    track_id: 'd9c74d9266af4d68f376f0fb9d5fb71c'


# Google.
google:
  # Google site verification
  site_verification: 'clzGAgkJY2WD5IGr5G6KZS9xymJYL_IH2QIEettmobY'
  # Google Analytics
  analytics:
    track_id: '' # Format: UA-xxxxxx-xx
    measurement_id: 'G-R9FFJYC4P1'
    domain: www.oscaner.com
  # Google Adsense
  adsense:
    data_ad_client: 'ca-pub-3286495153411959'
    # data_ad_client: ''

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: '未曾青梅，不见竹马.'
sidebar-avatar: 'https://q2.qlogo.cn/headimg_dl?bs=2573226076&dst_uin=2573226076&spec=640&url_enc=0&referer=bu_interface&term_type=PC' # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false


# Social share
social_share:
  enable: false
  sites:
    - qzone
    - qq
    - weibo
    - wechat
    - facebook
    - twitter


# Friends
friends: [
    {
        title: "Asdrt",
        href: "https://asdrt666.com",
        avatar: "https://asdrt666.com/usr/themes/handsome/usr/img/hade.png",
        description: "面朝大海，春暖花开。"
    },
    {
        title: "Choba·乔巴博客",
        href: "https://szdblog.com",
        avatar: "https://typechoblog-1256846006.cos.ap-beijing.myqcloud.com/2019/05/13/1557727134.jpg",
        description: ""
    },
    {
        title: "I BCL.",
        href: "https://ibcl.us/",
        avatar: "https://ibcl.us/images/avatar.jpg",
        description: "一位热爱无线电广播的高中学生"
    },
    {
        title: "mathor",
        href: "https://www.wmathor.com/",
        avatar: "https://img.hsxhn.com/images/2018/05/11/120x120.jpg",
        description: "热爱数学的程序员"
    },
    {
        title: "Mr. 童的博客",
        href: "https://tongtaos.com",
        avatar: "https://pt-1252677442.cos.ap-chengdu.myqcloud.com/IMG_0909.JPG",
        description: "Mr. 童的博客"
    },
    {
        title: "wantsget",
        href: "https://blog.kejijie.vip/",
        avatar: "https://q2.qlogo.cn/headimg_dl?bs=1836680478&dst_uin=1836680478&spec=100&url_enc=0&referer=bu_interface&term_type=PC",
        description: "划水程序猿"
    },
    {
        title: "三十三言",
        href: "https://o0o0o0.cn/",
        avatar: "https://o0o0o0.cn/wp-content/uploads/2018/05/nlogo.jpg",
        description: "穷尽此生，不得拥抱"
    },
    {
        title: "八个比特",
        href: "http://www.gazyip.cn/",
        avatar: "http://moments.gazyip.cn/file/avatar.png",
        description: "八个比特"
    },
    {
        title: "李学江博客",
        href: "https://www.lixuejiang.com/",
        avatar: "https://www.lixuejiang.com/common/img/tx.jpg",
        description: "实用的自媒体博客交流平台"
    },
    {
        title: "梁Sir的小站",
        href: "https://5sir.cn",
        avatar: "https://5sir.cn/logo.jpg",
        description: "[ 日久见人心 ]"
    },
    {
        title: "森纯个人博客",
        href: "http://isenchun.cn/",
        avatar: "http://isenchun.cn/logo.png",
        description: "记录大学的点点滴滴及学习之旅"
    },
    {
        title: "欧尼酱",
        href: "http://www.nothamor.cn/",
        avatar: "https://i.loli.net/2018/04/28/5ae46811094e6.jpg",
        description: "浑水摸鱼的咸鱼一条，伪Geek"
    },
    {
        title: "清酒踏月",
        href: "https://www.lkxin.cn",
        avatar: "https://img.lkxin.cn/tx.jpg",
        description: "成长的过程总是荆棘满路！"
    },
    {
        title: "烟雨寒云博客",
        href: "https://www.yyhy.me",
        avatar: "https://ws3.sinaimg.cn/large/006Xmmmggy1ft26nw45l3j30b40b4aa7",
        description: "一点烟雨,一点寒,风吹过,烟花散"
    },
    {
        title: "犬の窝",
        href: "http://mlldxe.cn",
        avatar: "http://mlldxe.cn/head/mlldxe.jpg",
        description: "一只菜狗，苣蒻，奄奄一息"
    },
    {
        title: "憧憬播客",
        href: "https://aoppp.com",
        avatar: "",
        description: "憧憬播客专注互联网产品开发"
    }
]
